apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJpbnRoZWdhbWUiLCJwYXNzd29yZCI6IlM0VmJMcW1dLUMhPUxuaCIsImVtYWlsIjoiaXRhaUBpbnRoZWdhbWUuaW8iLCJhdXRoIjoiYVc1MGFHVm5ZVzFsT2xNMFZtSk1jVzFkTFVNaFBVeHVhQT09In19fQ==
kind: Secret
metadata:
  name: regcredww
  namespace: php-itg-dev
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-api-dev
  name: php-api-dev
  namespace: php-itg-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: php-api-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: php-api-dev
    spec:
      containers:
      - image: inthegame/php_api_itg_dev6:5e308c4ebb0afab65e45ae8166325a65de0e1ff5
        imagePullPolicy: IfNotPresent
        name: php-api-dev
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcredww
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: php-dev-svc
  namespace: php-itg-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: php-api-dev
  sessionAffinity: None
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client_max_body_size: 500m
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/limit-rpm: "200"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  name: php-api-dev
  namespace: php-itg-dev
spec:
  rules:
  - host: itg-admin-dev6.inthegame.io
    http:
      paths:
      - backend:
          serviceName: php-dev-svc
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
